### ISSUE TITLE
running conda update --all inside the spyder terminal broke anaconda

### ISSUE THREAD

**Issue by math-is-fun** [spyder-ide/spyder-terminal#238]
## Description of your problem

**What steps will reproduce the problem?**

1. Run > conda update --all inside spyder terminal

**What is the expected output? What do you see instead?**
Expected: Normal update of all packages in the core environment

Instead: At some point during the update, it tried to open 127.0.0.1 (or a similar IP, I wasn't smart enough to write it down) after which the terminal became unresponsive and all subsequent terminals did not work. I tried to restart spyder, but after closing spyder, it no longer worked, nor did conda commands. I had to delete and reinstall anaconda.

**Please provide any additional information below**

## Versions and main components

Unfortunately, I deleted everything before I thought to make a bug complaint, sorry.

* Terminal Version: ¯\_(ツ)_/¯ 
* Spyder Version: ¯\_(ツ)_/¯ 
* Python Version: 3.7.7
* Operating system: Mac OS 10.15.6

**Comment by twelsh37** [comment]
This to me seems a systems issue. You should not be able to update Spyder from Inside Spyder. You could carry this out in old versions with problems arising. See file Spyder-4.0.1. In Later Versions of Spyder it was not possible to carry this out. See Spyder -4.1.4

Work PC Running Windows 10 1803 - File attached Spyder-4.1.4
Home PC running windows 10 1909 - File Attached Spyder-4.0.1

[Spyder-4.0.1.txt](https://github.com/spyder-ide/spyder-terminal/files/5155411/Spyder-4.0.1.txt)
[Spyder-4.1.4.txt](https://github.com/spyder-ide/spyder-terminal/files/5155412/Spyder-4.1.4.txt)

Seems to me that the issue was running the update from inside the Spyder IDE.
I am running windows 10, spyder 4.1.4 at work and I carried out the above.

When I tried the update inside the Spyder terminal it did all the checks and collection logic and was ready to proceed., On entering Y to continue it exited. I would expect this to be correct as it was trying to update itself from inside itself.  Results in Spyder-4.1.4

When I did the same on my home pc running windows 10 and Spyder 4.0.1 I got the results in Spyder-4.0.1 when was able to run the conda update --all from the Spyder Terminal within Spyder. I would not have expected to be allowed to do this. As i said above. in Spyder v 4.1.4 this is not the case.

Hopefully helpful to devs.

**Comment by math-is-fun** [comment]
Yeah, seems like it was a bonehead move on my part trying to update all from within one of the to be updated applications. Probably not something I should've tried to do in the first place. Well, I'm running 4.1.5 now, so I guess it is solved
