### ISSUE TITLE
Setting default font size

### ISSUE THREAD

**Issue by paraschakis** [spyder-ide/spyder-terminal#247]
## Description of your problem

It would be nice to have a setting for the default font size, because now for each new terminal window, a user must increase/decrease the font size manually.

**Comment by steff456** [comment]
Hi @paraschakis,

We tried to have a default font size, but the problem we encounter is that it depends on the screen resolution. That's why we decided to just manage the increase/decrease of the font. We could try to add this option to the configuration page so that new terminals that you open will have a certain zoom by default for our next release. 

Thanks for reporting!

**Comment by dkinneyBU** [comment]
TBH I'd be happy just being able to change the font size; manually or otherwise. I'm running Spyder 4.2.1. Can you enlighten me on how I can change the Windows cmd font size please? I'm sure I'm missing something obvious.
