### ISSUE TITLE
Shell interpreter: Anaconda Power Shell Prompt

### ISSUE THREAD

**Issue by MCilento93** [spyder-ide/spyder-terminal#250]
## Description of proposed enhancement

**Anaconda pre-activate shell interpreter**
![image](https://user-images.githubusercontent.com/66259011/106355898-6114d280-62fb-11eb-9f2d-3d942f7bd345.png)

I am running spyder-ide from a new created environment (not conda-base). I would like to access anaconda commands within syder-terminal, but the two shells proposed do not include "Anaconda Power Shell Prompt" or "Anaconda Prompt".

[In Atom or for batch commands I usually type "call C:\Users\mario\Anaconda3\Scripts\activate.bat" first in the cmd to activate Anaconda.](https://github.com/issues)

## Versions and main components

* Terminal Version: 0.5.0
* Spyder Version: 4.2.0
* Python Version: 3.8.5
* Operating system: Windows 10

**Comment by steff456** [comment]
Hi @MCilento93,

We currently don't support Anaconda power shell prompt but we can add it in our next release. This may take a while because we are working on a new API for Spyder 5, so once we have this covered we'll update the external plugins.

If you are interested in helping us adding this feature to spyder-terminal please let me know to give you the instructions you need.

Thanks for reporting!

**Comment by MCilento93** [comment]
> Hi @MCilento93,
> 
> We currently don't support Anaconda power shell prompt but we can add it in our next release. This may take a while because we are working on a new API for Spyder 5, so once we have this covered we'll update the external plugins.
> 
> If you are interested in helping us adding this feature to spyder-terminal please let me know to give you the instructions you need.
> 
> Thanks for reporting!

Dear Steff thank you for your kind answer! Sorry for replying you so late.
Anyway, for me it is ok helping you with this feature. 
Feel free to write me at your convenience mario.cilento.93@gmail.com

Regards 😄
