### ISSUE TITLE
Font size preference not respected

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder-terminal#301]
## Description of your problem

Font size in Spyder preferences is not respected. It appears that the font size in the Terminal plugin is always 16.

**What steps will reproduce the problem?**

1. Change font size in Spyder Preferences -> Appearance
2. Font size in Terminal plugin does not change

**What is the expected output? What do you see instead?**
Font size in Terminal plugin should change.

**Please provide any additional information below**
Note that the font _is_ respected. When changing the font in the preferences, the font in Terminal correctly updates, just not the font size.

## Versions and main components

* Terminal Version: 1.2.0
* Spyder Version: 5.2.1
* Python Version: 3.9.9
* Operating system: macOS 11.6.2

**Comment by steff456** [comment]
Hi @mrclary,

We decided not to match the font size from Spyder preferences because it doesn't match the look of the IDE. I could try to see if it works better in newer versions of xtermjs, but last time we tried it depended on the size of your screen how big or small the text will be shown. Our solution for that, was to include the zoom in/out feature as a replacement.
